/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import '@stencil/router';
import '@stencil/state-tunnel';
import 'ionicons';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ColorStreaks {}
  interface ColorStreaksAttributes extends StencilHTMLAttributes {}

  interface ColorTriangle {
    'animated': boolean;
    'color': string;
    'delayStep': number;
    'size': number;
  }
  interface ColorTriangleAttributes extends StencilHTMLAttributes {
    'animated'?: boolean;
    'color'?: string;
    'delayStep'?: number;
    'size'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'ColorStreaks': Components.ColorStreaks;
    'ColorTriangle': Components.ColorTriangle;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'color-streaks': Components.ColorStreaksAttributes;
    'color-triangle': Components.ColorTriangleAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLColorStreaksElement extends Components.ColorStreaks, HTMLStencilElement {}
  var HTMLColorStreaksElement: {
    prototype: HTMLColorStreaksElement;
    new (): HTMLColorStreaksElement;
  };

  interface HTMLColorTriangleElement extends Components.ColorTriangle, HTMLStencilElement {}
  var HTMLColorTriangleElement: {
    prototype: HTMLColorTriangleElement;
    new (): HTMLColorTriangleElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'color-streaks': HTMLColorStreaksElement
    'color-triangle': HTMLColorTriangleElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'color-streaks': HTMLColorStreaksElement;
    'color-triangle': HTMLColorTriangleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
